mass        : 3.2
gra         : 9.81
hov_percent : 0.506365041899
full_thrust : 100
ctrl_rate   : 200.0
js_ctrl_lock_velo: 0.3

hover:
    set_hov_percent_to_zero: false
    use_hov_percent_kf: true
    vert_velo_limit_for_update: 0.01
    vert_height_limit_for_update: 0.2
    percent_lower_limit: 0.1
    percent_higher_limit: 0.8

gain:
    hover:
        # Controller gain in minimun snap
        Kp0: 0.1
        Kp1: 0.1
        Kp2: 0.1
        Kv0: 3.0
        Kv1: 3.0
        Kv2: 3.0
        Kvi0: 0.3
        Kvi1: 0.3
        Kvi2: 0.3
        Ka0: 1.0
        Ka1: 1.0
        Ka2: 1.0
        Kr0: 0.5
        Kr1: 0.5
        Kr2: 0.1
        Kw0: 0.07
        Kw1: 0.07
        Kw2: 0.07
        Omega_p_roll: 2.0
        Omega_p_pitch: 2.0
        Omega_p_yaw: 2.0
        Omega_d_roll: 0.00
        Omega_d_pitch: 0.00
        Omega_d_yaw: 0.00
        ctrl_limit:
            pos_norm: 0.2
            spd_norm: 0.5
            f_norm: 2000.0
            switch_angle: 30.0  # switch to ctrl angle
    track:
        Kp0: 0.80
        Kp1: 0.80
        Kp2: 0.80
        Kv0: 3.0
        Kv1: 3.0
        Kv2: 3.0
        Kvi0: 0.1
        Kvi1: 0.1
        Kvi2: 0.1
        Ka0: 1.0
        Ka1: 1.0
        Ka2: 1.0
        Kr0: 0.5
        Kr1: 0.5
        Kr2: 0.1
        Kw0: 0.07
        Kw1: 0.07
        Kw2: 0.07
        Omega_p_roll: 2.0
        Omega_p_pitch: 2.0
        Omega_p_yaw: 2.0
        Omega_d_roll: 1.0
        Omega_d_pitch: 1.0
        Omega_d_yaw: 1.0
        ctrl_limit:
            pos_norm: 0.3
            spd_norm: 0.5
            f_norm: 2000.0
            switch_angle: 60.0  # switch to ctrl angle
idling:
    desired_height_limit:   -1.10
    desired_velo_limit:     0.10
    feedback_velo_limit:    0.10
    js_thrust_limit:        0.1
    landing_timeout:        1.0
    landing_thrust_percent: 0.6
    lowest_thrust:          0.05

rc:
    hori_velo_scale:   3.0
    vert_velo_scale:   3.0
    # rad 30~0.523 45~0.785 60~1.047
    yaw_scale:         0.523
    attitude_scale:    0.523
    deadzone:          0.1
    exit_cmd_deadzone: 0.2

msg_timeout:
    odom: 7
    rc: 0.2
    cmd: 7

